version: '3.8'


services:
  uk-antivirus:
    image: uk-antivirus
    container_name: uk-antivirus
    build:
      context: .
      dockerfile: Dockerfile

    #restart: always
    environment:
      - TZ=Europe/Warsaw
      - DM_APP_NAME="Antivirus"
      - PORT=5000
      - DM_ENVIRONMENT=development
      - DM_ANTIVIRUS_API_AUTH_TOKENS=token
      - DM_ANTIVIRUS_API_CALLBACK_AUTH_TOKENS=token
      - ROOT_PASSWORD=rootPAS#
      # Defaults OS environment config variables
      
    # volumes:
      # - /ai/config/dekretacja:/ai/config/dekretacja

#    network_mode: host
    ports:
      - 5455:5000
      - 5456:2222


#    entrypoint: /entrypoint.sh
    #entrypoint: "sleep infinity"

    #deploy:
    #  resources:
    #    reservations:
    #      devices:
    #        - capabilities: [ gpu ]

